Project_Vicostone/Controllers/AddProductController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using Project_Vicostone.Models;

namespace Project_Vicostone.Controllers
{
    public class AddProductController : BaseController
    {
        // GET: AddProduct
        private QuanLyAccountDbContext _db = new QuanLyAccountDbContext();
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index([Bind(Include = "Id,ProductName,ProductCode,Collections,ProductImage,TechnicalInfor,HueId,Material,Sizes")]Product imageModel, HttpPostedFileBase ImageFile)
        {
            string fileName = Path.GetFileNameWithoutExtension(ImageFile.FileName);
            string extension = Path.GetExtension(ImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            imageModel.ProductImage = "~/images/image-Product/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/images/image-Product"), fileName);
            ImageFile.SaveAs(fileName);
            if (ModelState.IsValid)
            {
                _db.Products.Add(imageModel);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(imageModel);
        }

        
    }
}

Project_Vicostone/Views/AddProduct/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Project_Vicostone.Models.Product

    <div class="wrap-login">
        <div class="login-form">
            <h3>Add-Product</h3>
            
            @using (Html.BeginForm("Index", "AddProduct", FormMethod.Post,new {enctype="multipart/form-data"}))
            {
                @Html.AntiForgeryToken()
                <div class="form">
                    <div class="form-group">
                        <label >Product Name <span class="require">*</span></label>
                        @Html.TextBoxFor(model => model.ProductName, new { @class = "form-control", @autofocus = "autofocus" })
                        @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label>Product Code <span class="require">*</span></label>
                        @Html.TextBoxFor(model => model.ProductCode, new { @class = "form-control", @autofocus = "autofocus" })
                        @Html.ValidationMessageFor(model => model.ProductCode, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label >Collections <span class="require">*</span></label>
                        @Html.TextBoxFor(model => model.Collections, new { @class = "form-control", @autofocus = "autofocus" })
                        @Html.ValidationMessageFor(model => model.Collections, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label>Product Image <span class="require">*</span></label>
                        <input type="file" name="ImageFile" required/>
                      @*  @Html.TextBoxFor(model => model.ProductImage, new { @class = "form-control", @autofocus = "autofocus" })*@
                       @* @Html.ValidationMessageFor(model => model.ProductImage, "", new { @class = "text-danger" })*@
                    </div>
                    <div class="form-group">
                        <label>Technical Infor <span class="require">*</span></label>
                        @Html.TextBoxFor(model => model.TechnicalInfor, new { @class = "form-control", @autofocus = "autofocus" })
                        @Html.ValidationMessageFor(model => model.TechnicalInfor, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label>Hues Id <span class="require">*</span></label>
                        @Html.TextBoxFor(model => model.HueId, new { @class = "form-control", @autofocus = "autofocus" })
                        @Html.ValidationMessageFor(model => model.HueId, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label>Material <span class="require">*</span></label>
                        @Html.TextBoxFor(model => model.Material, new { @class = "form-control", @autofocus = "autofocus" })
                        @Html.ValidationMessageFor(model => model.Material, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label>Sizes<span class="require">*</span></label>
                        @Html.TextBoxFor(model => model.Sizes, new { @class = "form-control", @autofocus = "autofocus" })
                        @Html.ValidationMessageFor(model => model.Sizes, "", new { @class = "text-danger" })
                    </div>
                   
                    <button type="submit" class="btn btn-default">Create</button>
                </div>
            }
        </div>
    </div>